[tool.pytest.ini_options]
pythonpath = "src"

[tool.pdm]
distribution = false

[project]
name = "bill"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Sung Cho", email = "sung.w.cho@pm.me"},
]
dependencies = ["google-api-python-client", "google-auth-httplib2", "google-auth-oauthlib", "flask"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "ipykernel",
    "pytest",
    "ruff",
    "black",
]
