name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install

    - name: Run Ruff check
      run: pdm run ruff check

    - name: Run Black check
      run: pdm run black --check .

    - name: Run tests
      run: |
        INFERENCE_API_TOKEN=dummy_token pdm run pytest
      env:
        INFERENCE_API_TOKEN: dummy_token

    - name: Run type checking (if mypy is configured)
      run: |
        if command -v mypy &> /dev/null; then
          pdm run mypy src/
        else
          echo "mypy not configured, skipping type checking"
        fi
      continue-on-error: true