name: Security Checks

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pdm install

    - name: Run security checks with Bandit
      run: |
        if command -v bandit &> /dev/null; then
          pdm run bandit -r src/ -f json -o bandit-report.json || true
        else
          echo "bandit not available, installing..."
          pdm add --group security bandit
          pdm run bandit -r src/ -f json -o bandit-report.json || true
        fi
      continue-on-error: true

    - name: Run dependency vulnerability scan
      run: |
        if command -v safety &> /dev/null; then
          pdm run safety check || true
        else
          echo "safety not available, installing..."
          pdm add --group security safety
          pdm run safety check || true
        fi
      continue-on-error: true